const CURR_USER_REQUEST   = 'CURR_USER_REQUEST';
const CURR_USER_SUCCESS   = 'CURR_USER_SUCCESS';
const CURR_USER_ERROR     = 'CURR_USER_ERROR';

export {CURR_USER_REQUEST,CURR_USER_SUCCESS,CURR_USER_ERROR}