const LOGIN_REQUEST   = 'LOGIN_REQUEST';
const LOGIN_SUCCESS   = 'LOGIN_SUCCESS';
const LOGIN_ERROR     = 'LOGIN_ERROR'     
const CURR_USER       = 'CURR_USER';

export {LOGIN_REQUEST,LOGIN_SUCCESS,LOGIN_ERROR,CURR_USER}